call_API(){
  RES=`$1`
  echo `date "+%Y-%m-%dT%H:%M:%S,"; echo $1`
}

call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-tags"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-tags"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-network-acls"
./updateACL.sh
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-tags"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-tags"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-instances"
call_API "aws ec2 describe-vpn-connections"
call_API "aws ec2 describe-vpn-gateways"
call_API "aws ec2 describe-customer-gateways"
call_API "aws ec2 describe-network-acls"
call_API "aws ec2 describe-security-groups"
call_API "aws ec2 describe-nat-gateways"
call_API "aws ec2 describe-vpc-endpoint-service-configurations"
call_API "aws ec2 describe-vpc-peering-connections"
call_API "aws ec2 describe-vpc-endpoints"
call_API "aws ec2 describe-addresses"
call_API "aws ec2 describe-route-tables"
call_API "aws ec2 describe-dhcp-options"
call_API "aws ec2 describe-internet-gateways"
call_API "aws ec2 describe-egress-only-internet-gateways"
call_API "aws ec2 describe-subnets"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-vpcs"
call_API "aws ec2 describe-regions"
